In [ ]:
import numpy as np

zer = np.zeros((2,5))
print(zer)
print(zer + 5)
print(zer.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
(2, 5)


In [ ]:
matrix = np.random.random((3,3))
print(matrix)
matrix.sort()
print(matrix)

[[0.97810581 0.03300301 0.57401922]
 [0.8025922  0.15062594 0.30296369]
 [0.36461104 0.47068329 0.78478469]]
[[0.03300301 0.57401922 0.97810581]
 [0.15062594 0.30296369 0.8025922 ]
 [0.36461104 0.47068329 0.78478469]]


In [ ]:
print(np.random.randint(1, 5, (3,4)))

[[2 3 4 1]
 [4 1 3 1]
 [4 4 3 4]]


In [ ]:
x = np.linspace(0,4,10)
print(x)

[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]


In [ ]:
print(x.mean(), x.sum(), x.max())

2.0 20.0 4.0


In [ ]:
x2 = np.reshape(x, (5, 2))
print(x2)
print(x2.shape)
print(x2.mean())
print(x2.sum())

[[0.         0.44444444]
 [0.88888889 1.33333333]
 [1.77777778 2.22222222]
 [2.66666667 3.11111111]
 [3.55555556 4.        ]]
(5, 2)
2.0
20.0


In [ ]:
y = np.linspace(0,4,10).reshape(-1,1)
print(y)

[[0.        ]
 [0.44444444]
 [0.88888889]
 [1.33333333]
 [1.77777778]
 [2.22222222]
 [2.66666667]
 [3.11111111]
 [3.55555556]
 [4.        ]]


In [ ]:
print(x @ y) # np.dot(x,y)
print((y**2).sum())

[56.2962963]
56.29629629629629


In [ ]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[8 2 0 3 6 4 9 1 5 7]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A[:, ::-1]
print(A)
print(B)
B[1][1] = 0
print(A)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 0 6]]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A.copy()[:, ::-1]
print(A)
print(B)
B[1][1] = 0
print(A)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


In [ ]:
x = np.random.random((2,4))
print(x)
print(x.T)

[[0.69515204 0.54205252 0.41990039 0.54295413]
 [0.82804678 0.20929654 0.74152849 0.70543345]]
[[0.69515204 0.82804678]
 [0.54205252 0.20929654]
 [0.41990039 0.74152849]
 [0.54295413 0.70543345]]
